sudo: required
services:
  - docker

before_install:
  - docker build -t rcamsan/react-test -f./client/Dockerfile.dev ./client

script:
    - docker run rcamsan/react-test npm test -- --coverage

after_success:
  docker build -t rcamsan/multi-client ./client
  docker build -t rcamsan/multi-nginx ./nginx
  docker build -t rcamsan/multi-server ./server
  docker build -t rcamsan/multi-worker ./worker

#Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" password-stdin

# Take these images and push
- docker push rcamsan/multi-client ./client
- docker push rcamsan/multi-nginx ./nginx
- docker push rcamsan/multi-server ./server
- docker push rcamsan/multi-worker ./worker
